version: '3.3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13
    container_name: foodgram_db
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    image: alexproevolution/foodgram_backend:latest
    container_name: foodgram_backend
    env_file: .env
    depends_on:
      - db
    volumes:
      - static:/app/static
      - media:/app/media
    expose:
      - "7000"
    command: ["gunicorn", "--bind", "0.0.0.0:7000", "foodgram.wsgi"]
  
    frontend:
      image: alexproevolution/foodgram_frontend:latest
      env_file: .env
      command: cp -r /app/build/. /frontend_static/
      volumes:
        - static:/frontend_static

  gateway:
    image: alexproevolution/foodgram_gateway:latest
    env_file: .env
    depends_on:
      - backend
      - frontend
    volumes:
      - static:/app/staticfiles
      - media:/app/media
    ports:
      - 7000:80