volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13
    container_name: foodgram_db
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    build: ./backend/
    container_name: foodgram_backend
    env_file: .env
    depends_on:
      - db
    volumes:
      - static:/app/static
      - media:/app/media

  frontend:
    container_name: foodgram-front
    build: ./frontend
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static:/frontend_static

  gateway:
    build: ./infra/
    env_file: .env
    container_name: foodgram_gateway
    ports:
      - 7000:80
    volumes:
      - static:/app/static
      - media:/app/media