version: '3.3'

volumes:
  postgres_data:
  static_value:
  media_value:

services:
  db:
    image: postgres:13
    container_name: db
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    image: alexproevolution/foodgram_backend:latest
    container_name: foodgram_backend
    env_file: .env
    volumes:
      - static_value:/code/static_backend/
      - media_value:/code/media/
    depends_on:
      - db

  frontend:
    image: alexproevolution/foodgram_frontend:latest
    container_name: foodgram_frontend
    env_file: .env
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static:/frontend_static
    depends_on:
      - backend

  gateway:
    image: alexproevolution/foodgram_gateway 
    container_name: foodgram_gateway
    env_file: .env
    ports:
      - "7000:80"
    volumes:
      - ../frontend/build:/usr/share/nginx/html/
      - ./docs/:/usr/share/nginx/html/api/docs/
      - static:/static/
      - media:/app/media/
    depends_on:
      - frontend