# Generated by Django 3.2.16 on 2025-06-25 15:47

import shortuuid.main
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_auto_20250625_0203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='short_code',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, max_length=50, unique=True, verbose_name='Короткий код'),
        ),
    ]
