# Generated by Django 3.2.16 on 2025-06-24 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20250624_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=250, unique=True, verbose_name='Адрес электронной почты'),
        ),
    ]
